/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

import cdkExports from './cdk-exports';

const awsmobile = {
  aws_project_region: 'ap-southeast-1',

  aws_appsync_graphqlEndpoint: cdkExports.API_URL,
  aws_appsync_region: 'ap-southeast-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
  aws_appsync_apiKey: undefined,
  // aws_cognito_identity_pool_id: 'ap-southeast-1:b518ad59-fd95-44b7-aca6-c500b5800119',
  aws_cognito_region: 'ap-southeast-1',
  aws_user_pools_id: cdkExports.USER_POOL_ID,
  aws_user_pools_web_client_id: cdkExports.WEB_APP_CLIENT_ID,
  // oauth: {
  //   domain: 'swtninjaauth-dev-compapi.auth.ap-southeast-1.amazoncognito.com',
  //   scope: ['phone', 'email', 'openid', 'profile', 'aws.cognito.signin.user.admin'],
  //   redirectSignIn: 'http://localhost:3000/profile/',
  //   redirectSignOut: 'http://localhost:3000/profile/',
  //   responseType: 'code',
  // },
  federationTarget: 'COGNITO_USER_POOLS',
  aws_content_delivery_bucket: 'wakeninja-compapi',
  aws_content_delivery_bucket_region: 'ap-southeast-1',
  aws_content_delivery_url: 'http://wakeninja-compapi.s3-website-ap-southeast-1.amazonaws.com',
};

export default awsmobile;
